import React, { useState } from 'react';
import { Sparkles, ShieldCheck, AlertTriangle, ChevronDown, ChevronRight } from 'lucide-react';
import { Explanation } from '../types';

interface ExplanationPanelProps {
  explanation: Explanation | null;
  loading: boolean;
  title?: string;
}

// Renders an LLM explanation sentence by sentence; each citation marker shows the cited fact on hover.
export const ExplanationPanel: React.FC<ExplanationPanelProps> = ({ explanation, loading, title = 'Plain-language explanation' }) => {
  const [showFacts, setShowFacts] = useState(false);

  if (loading) {
    return (
      <div className="bg-emerald-50 p-4 rounded-xl border border-emerald-200 text-xs text-emerald-800 flex items-center space-x-2">
        <div className="h-4 w-4 border-2 border-emerald-400 border-t-transparent rounded-full animate-spin shrink-0"></div>
        <span>Writing a cited explanation with the local model (can take up to a minute the first time)...</span>
      </div>
    );
  }
  if (!explanation) return null;

  const factsById = Object.fromEntries(explanation.facts.map((f) => [f.id, f]));
  const isLLM = explanation.source === 'llm';

  return (
    <div className="bg-emerald-50 p-4 rounded-xl border border-emerald-200 text-xs space-y-3">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <span className="font-bold text-emerald-700 uppercase tracking-wider text-[10px] flex items-center space-x-1.5">
          <Sparkles className="h-3.5 w-3.5" />
          <span>{title}</span>
        </span>
        <span className="text-[10px] text-slate-500">
          {isLLM ? `AI-generated by ${explanation.model}${explanation.cached ? ' (cached)' : ''}` : 'Template text (model unavailable)'}
        </span>
      </div>

      {isLLM ? (
        <p className="text-emerald-900 leading-relaxed">
          {explanation.sentences.map((s, i) => (
            <span key={i}>
              {s.text}
              {s.facts.map((fid) => (
                <sup
                  key={fid}
                  title={factsById[fid]?.text}
                  className="ml-0.5 px-1 rounded bg-emerald-100 text-emerald-700 font-mono text-[9px] cursor-help"
                >
                  {fid}
                </sup>
              ))}{' '}
            </span>
          ))}
        </p>
      ) : (
        <p className="text-emerald-900 leading-relaxed">{explanation.text}</p>
      )}

      <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-[10px] text-slate-500">
        {isLLM && (
          <span className="flex items-center space-x-1">
            <ShieldCheck className="h-3 w-3 text-emerald-600" />
            <span>
              Every sentence cites atlas facts; {explanation.dropped.length} sentence(s) removed by the citation and number check.
              Wording can still overstate a fact, so check the cited facts.
            </span>
          </span>
        )}
        {!isLLM && explanation.error && (
          <span className="flex items-center space-x-1">
            <AlertTriangle className="h-3 w-3 text-amber-700" />
            <span>{explanation.error}</span>
          </span>
        )}
      </div>

      <button onClick={() => setShowFacts(!showFacts)} className="flex items-center space-x-1 text-[10px] text-slate-500 hover:text-slate-800">
        {showFacts ? <ChevronDown className="h-3 w-3" /> : <ChevronRight className="h-3 w-3" />}
        <span>Facts given to the model ({explanation.facts.length})</span>
      </button>
      {showFacts && (
        <ul className="space-y-1 text-[11px] text-slate-700">
          {explanation.facts.map((f) => (
            <li key={f.id}>
              <span className="font-mono text-emerald-600 mr-1">{f.id}</span>
              {f.text}
            </li>
          ))}
        </ul>
      )}
    </div>
  );
};
